services:
  api:
    build: ./backend
    container_name: api-ps
    command: uv run manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env.dev
    ports:
      - 8000:8000
    depends_on:
      - db

  web:
    build: ./frontend
    container_name: web-ps
    command: npm run dev
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
    depends_on:
      - api

  db:
    image: postgres:17-alpine
    container_name: db-ps
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./backend/.env.dev

volumes:
  postgres_data: