# Generated by Django 5.1.6 on 2025-03-14 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
